services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
    security_opt:
      - no-new-privileges=true
    ports:
      - "80:80"
      - "443:443"

      - "8080:8080"
      - "2222:2222"

      # RDP
      - "3389:3389/tcp"
      - "3389:3389/udp"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - "./traefik:/etc/traefik"
      - "./traefik/plugins-storage:/plugins-storage"
    environment:
      - TZ
      - CF_DNS_API_TOKEN
      - PUID
      - PGID
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      traefik:
        ipv6_address: "2001:db8:2::2"
        ipv4_address: "172.21.0.2"

  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      - USER=crowdsec
      - GID
      - COLLECTIONS
      - CUSTOM_HOSTNAME
      - TZ
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 6060:6060
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - crowdsec_config:/etc/crowdsec:rw
      - crowdsec_data:/var/lib/crowdsec/data:rw
      - ./crowdsec/config/acquis.d:/etc/crowdsec/acquis.d:ro
      - ./crowdsec/config/notifications:/etc/crowdsec/notifications:ro
      - ./crowdsec/config/config.yaml:/etc/crowdsec/config.yaml:rw
      - ./crowdsec/config/profiles.yaml:/etc/crowdsec/profiles.yaml:ro
      - ./crowdsec/logs:/var/log/crowdsec:rw
      - ./traefik/logs:/var/log/traefik:ro
    healthcheck:
      test: ["CMD", "cscli", "lapi", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      traefik:
        ipv6_address: "2001:db8:2::3"
        ipv4_address: "172.21.0.3"

  cs-routeros-bouncer:
    image: ghcr.io/jmrplens/cs-routeros-bouncer:latest
    container_name: cs-routeros-bouncer
    restart: unless-stopped
    user: "$PUID:$PGID"
    depends_on:
      crowdsec:
        condition: service_healthy
    ports:
      - "2112:2112" # Prometheus metrics (optional)
    volumes:
      - ./routeros/config.yaml:/etc/cs-routeros-bouncer/config.yaml
      - ./routeros/logs:/var/log
    networks:
      traefik:
        ipv6_address: "2001:db8:2::7"
        ipv4_address: "172.21.0.7"

  anubis:
    image: ghcr.io/techarohq/anubis:main
    container_name: anubis
    restart: unless-stopped
    user: "$PUID:$PGID"
    depends_on:
      crowdsec:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges=true
    expose:
      - 8923
    ports:
      - 9191:9090
    environment:
      - BIND
      - DIFFICULTY
      - SERVE_ROBOTS_TXT
      - TARGET
      - POLICY_FNAME
      - TZ
      - REDIRECT_DOMAINS
      - PUBLIC_URL
      - COOKIE_DOMAIN
      - JWT_RESTRICTION_HEADER
      - USE_REMOTE_ADDRESS
      - ED25519_PRIVATE_KEY_HEX
    env_file:
      - .env
    volumes:
      - ./anubis:/data
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    networks:
      traefik:
        ipv6_address: "2001:db8:2::4"
        ipv4_address: "172.21.0.4"

# redis:
#   image: redis:7-alpine
#   container_name: traefik-redis
#   restart: unless-stopped
#   healthcheck:
#     test: ["CMD", "redis-cli", "--ping"]
#     interval: 30s
#     timeout: 5s
#     retries: 3
#   volumes:
#     - traefik_redis:/data
#   networks:
#     traefik:
#       ipv6_address: "2001:db8:2::6"
#       ipv4_address: "172.21.0.6"

#  traefik-manager:
#    image: ghcr.io/chr0nzz/traefik-manager:latest
#    container_name: traefik-manager
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges=true
#    ports:
#      - 5000:5000
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#    environment:
#      - COOKIE_SECURE
#      - RESTART_METHOD
#      - TRAEFIK_CONTAINER
#      - STATIC_CONFIG_PATH
#      - ACME_JSON_PATH
#      - ACCESS_LOG_PATH
#    env_file:
#      - .env
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      # Required
#      - ./traefik/dynamic.yml:/app/config/dynamic.yml
#      - ./manager/config:/app/config
#      - ./manager/backups:/app/backups
#      # Optional monitoring
#      - ./traefik/traefik.yml:/app/traefik.yml
#      - ./traefik/ssl/acme.json:/app/acme.json:ro
#      - ./traefik/logs/access.log:/app/logs/access.log:ro
#    networks:
#      traefik:
#        ipv6_address: "2001:db8:2::5"
#        ipv4_address: "172.21.0.5"

volumes:
  crowdsec_config:
  crowdsec_data:
  traefik_redis:

networks:
  traefik:
    name: traefik
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.21.0.0/16" # Change according to your needs
        - subnet: "2001:db8:2::/64"
    driver_opts:
          com.docker.network.driver.mtu: 1300

# Static ips on containers only for if you use the app.crowdsec.net, if you don't use the networks,
# the remediation components will have duplicated bouncers, each time you restart the container will get a new ip