global:
  checkNewVersion: true
  sendAnonymousUsage: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  traefik:
    address: "[::]:8080"

  http:
    address: "[::]:80"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "::1/128"
        - "fc00::/7"
    http:
      middlewares:
        - geoblock@file
        - anubis@file
        - crowdsec@file
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: "[::]:443"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "::1/128"
        - "fc00::/7"
    transport:
      respondingTimeouts:
        readTimeout: 3610s
    http:
      encodedCharacters:  
        allowEncodedSlash: true
        allowEncodedQuestionMark: true
        allowEncodedPercent: true
      middlewares:
        - geoblock@file
        - anubis@file
        - crowdsec@file

  ssh:
    address: "[::]:2222"

  rdp:
    address: "[::]:3389"

  rdp-udp:
    address: "[::]:3389/udp"

api:
  dashboard: true
  insecure: true

ping:
  entryPoint: traefik

log:
  filePath: /etc/traefik/logs/traefik.log
  level: INFO
  format: json

accessLog:
  filePath: /etc/traefik/logs/access.log
  format: json
  filters:
    # statusCodes:
    #   - "200"
    #   - "300-302"
    # retryAttempts: true
    # minDuration: "10ms"
  fields:
    # Keep all the fields by default
    defaultMode: keep
    names:
      # Drop the Field ClientUserName
      ClientUsername: drop
    headers:
      # Keep all the headers by default
      defaultMode: keep
      names:
        # Redact the User-Agent header value
        User-Agent: redact
        # Drop the Authorization header value
        Authorization: drop
    queryParameters:
      # Drop all query parameters
      defaultMode: drop

  # filters:
  #   statusCodes:
  #     - "200"
  #     - "400-599"
  #     - "500-599"
  #   retryAttempts: true
  #   minDuration: "10ms"
  # bufferingSize: 0
  # fields:
  #   headers:
  #     defaultMode: drop
  #     names:
  #       User-Agent: keep

providers:
  file:
    directory: /etc/traefik/config
    watch: true

  # redis:
  #   endpoints:
  #     - "traefik-redis:6379"
  #   rootKey: "traefik"

certificatesResolvers:
  cloudflare:
    acme:
      email: henriquebuffon@gmail.com
      storage: /etc/traefik/ssl/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

experimental:
  plugins:
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.6.0

    geoblock:
      moduleName: github.com/PascalMinder/geoblock
      version: v0.3.7

    themepark:
        moduleName: "github.com/packruler/traefik-themepark"
        version: "v1.4.2"