global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  http:
    address: "[::]:80"
    http:
      middlewares:
        - crowdsec@file
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: "[::]:443"
    http:
      middlewares:
        - crowdsec@file
      tls:
        certResolver: cloudflare

api:
  dashboard: true
  insecure: true

ping: {}

log:
  filePath: /etc/traefik/logs/traefik.log
  level: INFO
  format: json

accessLog:
  filePath: /etc/traefik/logs/access.log
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-599"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: henriquebuffon@gmail.com
      storage: /etc/traefik/ssl/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

experimental:
  plugins:
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.6.0