tcp:
  routers:
    mailcow-https:
      entryPoints:
        - https
      rule: "HostSNI(`mail.buffon.cloud`) || HostSNI(`autoconfig.buffon.cloud`) || HostSNI(`autodiscover.buffon.cloud`)"
      service: mailcow-https
      tls:
        passthrough: true

    dns:
      entryPoints:
        - https
      rule: "HostSNI(`dns.buffon.cloud`)"
      service: dns
      tls:
        passthrough: true

  services:
    mailcow-https:
      loadBalancer:
        servers:
          - address: "10.84.181.251:443"

    dns:
      loadBalancer:
        servers:
          - address: "10.84.181.242:443"