global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  http:
    address: "[::]:80"
    http:
      middlewares:
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: "[::]:443"
    http:
      middlewares:
        - crowdsec-bouncer@file
      tls:
        certResolver: cloudflare

api:
  dashboard: true
  insecure: true

ping: {}

log:
  level: DEBUG
  filePath: /logs/traefik.log

accesslog:
  filePath: /logs/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: henriquebuffon@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"